
export const weights = {
  thin: 100,
  light: 300,
  regular: 400,
  medium: 500,
  bold: 700,
  black: 900,
}

export const defaultTypography = {
  leading: {
    display4: '112px',
    display3: '56px',
    display2: '48px',
    display1: '40px',
    headline: '32px',
    title: '28px',
    subhead2: '28px',
    subhead1: '24px',
    body2: '24px',
    body1: '20px',
    caption: '20px',
    button: '36px',
  },
  tracking: {
    display4: '-0.01em',
    display3: '-0.005em',
    display2: '0',
    display1: '0',
    headline: '0',
    title: '0.005em',
    subhead2: '0.01em',
    subhead1: '0.01em',
    body2: '0.01em',
    body1: '0.01em',
    caption: '0.02em',
    button: '0.01em',
  },
  size: {
    display4: '112px',
    display3: '56px',
    display2: '45px',
    display1: '34px',
    headline: '24px',
    title: '20px',
    subhead2: '16px',
    subhead1: '15px',
    body2: '13px',
    body1: '13px',
    caption: '12px',
    button: '14px',
  },
  weight: {
    display4: weights.light,
    display3: weights.regular,
    display2: weights.regular,
    display1: weights.regular,
    headline: weights.medium,
    title: weights.regular,
    subhead2: weights.regular,
    subhead1: weights.regular,
    body2: weights.medium,
    body1: weights.regular,
    caption: weights.regular,
    button: weights.medium,
  },
  transform: {
    display4: 'inherit',
    display3: 'inherit',
    display2: 'inherit',
    display1: 'inherit',
    headline: 'inherit',
    title: 'inherit',
    subhead2: 'inherit',
    subhead1: 'inherit',
    body2: 'inherit',
    body1: 'inherit',
    caption: 'inherit',
    button: 'uppercase',
  },
}
